### ISSUE TITLE
Use upstream tcell?

### ISSUE THREAD

**Issue by n-peugnet** [tulir/mauview#10]
From what I see in the diffs, the only meaningful changes remaining in the fork is https://github.com/tulir/tcell/commit/11b8e487f8572cef42a6f2c04afc4ce0395112d7. Wouldn't be a good idea to try to upstream this commit and use the upstream version of tcell afterwards ?

I can make the changes and the pull request to tcell if you are ok with this, or maybe there is another reason why you prefer keeping a fork of tcell ?

**Comment by tulir** [comment]
https://github.com/gdamore/tcell/issues/622 / https://github.com/gdamore/tcell/pull/97

**Comment by nileshpatra** [comment]
According to gdamore/tcell author, `ButtonNone` is enough to indicate drags. I haven't read through mauview code - do you find it a possibility to fix the code with this hint?

**Comment by nileshpatra** [comment]
@tulir ping?

**Comment by tulir** [comment]
It's probably possible to use upstream, but requires refactoring the drag detection to remember previous buttons, so not currently planned
